base_model: Qwen/Qwen3-8B
# Automatically upload checkpoint and final model to HF
hub_model_id: samagra-tensorfuse/qwen-ft

plugins:
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
strict: false

chat_template: qwen3
datasets:
  - path: NousResearch/hermes-function-calling-v1
    name: func_calling_singleturn
    type: chat_template
    split: train[:80%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value
    # Role mappings (Hermes uses different role names)
    roles:
      assistant:
        - gpt
        - assistant
      user:
        - human
        - user
      system:
        - system
    roles_to_train: [assistant]
val_set_size: 0.05
output_dir: ./outputs/out
dataset_prepared_path: last_run_prepared

sequence_len: 2048
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

load_in_4bit: true
adapter: qlora
lora_r: 16
lora_alpha: 32
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - down_proj
  - up_proj
lora_mlp_kernel: true
lora_qkv_kernel: true
lora_o_kernel: true

wandb_project: qwen-finetuning
wandb_entity: samagra14-tensorfuse
wandb_watch:
wandb_name: tensorfuse-qwen
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 8
num_epochs: 3
optimizer: adamw_torch_4bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
tf32: true

gradient_checkpointing: offload
gradient_checkpointing_kwargs:
  use_reentrant: false
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
saves_per_epoch: 1
weight_decay: 0.0
special_tokens: